// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwH3kyLGbfeOTMGpZqdJ5AIXHzKVO4Eqs',
    appId: '1:366217616701:web:bd148bf59913fd4bb2f954',
    messagingSenderId: '366217616701',
    projectId: 'lucious-5f934',
    authDomain: 'lucious-5f934.firebaseapp.com',
    storageBucket: 'lucious-5f934.firebasestorage.app',
    measurementId: 'G-X0Q1QBHJPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5seosyW-ePEIoWKjExv7L_CIkDY72l_I',
    appId: '1:366217616701:android:e4a6fe6ade1e8b2bb2f954',
    messagingSenderId: '366217616701',
    projectId: 'lucious-5f934',
    storageBucket: 'lucious-5f934.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr0y3kWaK2oMdQRVXf6cwRAXeBwDo3mRM',
    appId: '1:366217616701:ios:810ac4fe502897b5b2f954',
    messagingSenderId: '366217616701',
    projectId: 'lucious-5f934',
    storageBucket: 'lucious-5f934.firebasestorage.app',
    iosBundleId: 'com.example.figmaCreationTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr0y3kWaK2oMdQRVXf6cwRAXeBwDo3mRM',
    appId: '1:366217616701:ios:810ac4fe502897b5b2f954',
    messagingSenderId: '366217616701',
    projectId: 'lucious-5f934',
    storageBucket: 'lucious-5f934.firebasestorage.app',
    iosBundleId: 'com.example.figmaCreationTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwH3kyLGbfeOTMGpZqdJ5AIXHzKVO4Eqs',
    appId: '1:366217616701:web:41a5b7ea4ba93686b2f954',
    messagingSenderId: '366217616701',
    projectId: 'lucious-5f934',
    authDomain: 'lucious-5f934.firebaseapp.com',
    storageBucket: 'lucious-5f934.firebasestorage.app',
    measurementId: 'G-S4ZKPJ1DPQ',
  );
}
